In [74]:
import pandas as pd
import numpy as np

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [76]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [77]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [78]:
df.shape

(13320, 9)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [80]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [81]:
df.drop(columns='society', inplace=True)

In [82]:
df.isna().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [83]:
imputer=  SimpleImputer(strategy='mean')
df['bath'] = imputer.fit_transform(df[['bath']])

In [84]:
df.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [85]:
df.isna().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath              0
balcony         609
price             0
dtype: int64

In [86]:
imputer1 = SimpleImputer(strategy='median')
df['balcony']= imputer.fit_transform(df[['balcony']])

In [87]:
df.sample(5)

,area_type,availability,location,size,total_sqft,bath,balcony,price
12217,Super built-up Area,20-Jan,Whitefield,2 BHK,1276,2.0,1.0,69.5
5338,Super built-up Area,Ready To Move,Venkatadri Layout,1 BHK,600,1.0,1.0,43.0
10733,Super built-up Area,Ready To Move,Basavangudi,3 BHK,1850,3.0,2.0,150.0
11321,Super built-up Area,Ready To Move,Bannerghatta Road,3 BHK,1550,3.0,2.0,96.0
8462,Built-up Area,Ready To Move,BHEL Layout,6 Bedroom,2400,4.0,1.0,170.0

In [88]:
df[df['total_sqft'].str.contains('-', na=False)]['total_sqft']

30       2100 - 2850
56       3010 - 3410
81       2957 - 3450
122      3067 - 8156
137      1042 - 1105
            ...
12990    1804 - 2273
13059    1200 - 1470
13240    1020 - 1130
13265    1133 - 1384
13299    2830 - 2882
Name: total_sqft, Length: 201, dtype: object

In [89]:
def convert_sqft(x):
    if isinstance(x, str):
        tokens = x.split('-')
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

In [90]:
df.sample(5)

,area_type,availability,location,size,total_sqft,bath,balcony,price
11020,Super built-up Area,18-Aug,Hennur Road,2 BHK,1232.0,2.0,1.0,69.61
9254,Super built-up Area,18-Dec,Harlur,2 BHK,1386.0,2.0,2.0,85.00
9974,Plot Area,Ready To Move,Sector 1 HSR Layout,3 Bedroom,2400.0,6.0,2.0,775.00
2942,Super built-up Area,Ready To Move,Whitefield,2 BHK,1320.0,2.0,1.0,95.00
1348,Super built-up Area,18-Mar,Kathriguppe,3 BHK,1650.0,3.0,2.0,125.00

In [91]:
df.isna().sum()

area_type        0
availability     0
location         1
size            16
total_sqft      46
bath             0
balcony          0
price            0
dtype: int64

In [92]:
df = df.dropna(subset=['size'])

In [93]:
df['bhk'] = df['size'].str.extract('(\d+)')[0].astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\ganvi\AppData\Local\Temp\ipykernel_22068\1507271465.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['bhk'] = df['size'].str.extract('(\d+)')[0].astype(int)

In [94]:
df.sample(5)

,area_type,availability,location,size,total_sqft,bath,balcony,price,bhk
8827,Plot Area,Ready To Move,Anandapura,3 Bedroom,1200.0,2.0,0.0,66.0,3
9175,Super built-up Area,21-May,Dairy Circle,3 BHK,2048.0,3.0,2.0,206.0,3
5108,Super built-up Area,Ready To Move,Old Madras Road,3 BHK,2266.0,3.0,2.0,169.0,3
6957,Super built-up Area,19-Jul,Kanakpura Road,3 BHK,1593.0,3.0,1.0,118.0,3
6057,Super built-up Area,18-May,Yelahanka,1 BHK,602.0,1.0,1.0,26.0,1

In [95]:
df= df.dropna(subset=['location'])

In [96]:
df.duplicated().sum()

569

In [97]:
df.drop_duplicates(inplace=True)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12734 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12734 non-null  object
 1   availability  12734 non-null  object
 2   location      12734 non-null  object
 3   size          12734 non-null  object
 4   total_sqft    12689 non-null  float64
 5   bath          12734 non-null  float64
 6   balcony       12734 non-null  float64
 7   price         12734 non-null  float64
 8   bhk           12734 non-null  int32
dtypes: float64(4), int32(1), object(4)
memory usage: 945.1+ KB

In [100]:
df.corr(numeric_only=True)

            total_sqft      bath   balcony     price       bhk
total_sqft    1.000000  0.387698  0.134096  0.573935  0.344673
bath          0.387698  1.000000  0.179048  0.452125  0.897970
balcony       0.134096  0.179048  1.000000  0.102563  0.166640
price         0.573935  0.452125  0.102563  1.000000  0.394935
bhk           0.344673  0.897970  0.166640  0.394935  1.000000

In [101]:
df.cov(numeric_only=True)

              total_sqft        bath     balcony          price         bhk
total_sqft  1.591768e+06  662.175972  135.966099  109926.965431  569.851579
bath        6.621760e+02    1.839594    0.195254      93.028452    1.599509
balcony     1.359661e+02    0.195254    0.646457      12.509935    0.175959
price       1.099270e+05   93.028452   12.509935   23014.016538   78.683827
bhk         5.698516e+02    1.599509    0.175959      78.683827    1.724754