In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_csv('Bengaluru_House_Data.csv')

In [4]:
df.shape

(13320, 9)

In [5]:
df.isna().sum() #missing values number

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [6]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [8]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [9]:
df['bath'].fillna(df['bath'].median(), inplace=True)

C:\Users\ganvi\AppData\Local\Temp\ipykernel_13332\3321556508.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bath'].fillna(df['bath'].median(), inplace=True)

In [10]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath               0
balcony          609
price              0
dtype: int64

In [11]:
df.drop_duplicates()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [12]:
df.drop(columns='society', inplace=True)

In [13]:
df.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [14]:
df[df['size'].isnull()]

,area_type,availability,location,size,total_sqft,bath,balcony,price
579,Plot Area,Immediate Possession,Sarjapur Road,NaN,1200 - 2400,2.0,NaN,34.185
1775,Plot Area,Immediate Possession,IVC Road,NaN,2000 - 5634,2.0,NaN,124.000
2264,Plot Area,Immediate Possession,Banashankari,NaN,2400,2.0,NaN,460.000
2809,Plot Area,Immediate Possession,Sarjapur Road,NaN,1200 - 2400,2.0,NaN,28.785
2862,Plot Area,Immediate Possession,Devanahalli,NaN,1500 - 2400,2.0,NaN,46.800
5333,Plot Area,Immediate Possession,Devanahalli,NaN,2100 - 5405,2.0,NaN,177.115
6423,Plot Area,Immediate Possession,Whitefield,NaN,2324,2.0,NaN,26.730
6636,Plot Area,Immediate Possession,Jigani,NaN,1500,2.0,NaN,25.490
6719,Plot Area,Immediate Possession,Hoskote,NaN,800 - 2660,2.0,NaN,28.545
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,5000,2.0,NaN,400.000
8306,Plot Area,Immediate Possession,Anekal,NaN,1453,2.0,NaN,16.500
8565,Plot Area,Immediate Possession,Carmelaram,NaN,2000,2.0,NaN,120.000
8703,Plot Area,Immediate Possession,Mysore Road,NaN,1200 - 2400,2.0,NaN,42.300
10634,Plot Area,Immediate Possession,Rajankunte,NaN,1575,2.0,NaN,31.110
11019,Plot Area,Immediate Possession,Yelahanka,NaN,1200 - 1800,2.0,NaN,12.750
11569,Plot Area,Immediate Possession,Hosur Road,NaN,1350,2.0,NaN,8.440

In [15]:
df = df.dropna(subset=['size'])

df['bhk'] = df['size'].str.extract('(\d+)')[0].astype(int)

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\ganvi\AppData\Local\Temp\ipykernel_13332\1074862514.py:3: SyntaxWarning: invalid escape sequence '\d'
  df['bhk'] = df['size'].str.extract('(\d+)')[0].astype(int)

In [16]:
df.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00,2

In [17]:
def convert_sqft_to_num(x):
    tokens = x.split('-')

    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1]))/2

    try:
        return float(x)
    except:
        return None

In [18]:
df.sample(7)

,area_type,availability,location,size,total_sqft,bath,balcony,price,bhk
5717,Super built-up Area,22-May,Jakkur,4 BHK,3405.1,6.0,3.0,400.0,4
8938,Built-up Area,Ready To Move,Electronic City,2 BHK,1150,2.0,2.0,35.0,2
5066,Built-up Area,Ready To Move,Rayasandra,3 BHK,1199,2.0,1.0,48.5,3
3687,Super built-up Area,19-Dec,Binny Pete,2 BHK,1365,2.0,1.0,122.0,2
2360,Built-up Area,Ready To Move,HMT Layout,3 BHK,1700,3.0,NaN,80.0,3
9477,Super built-up Area,18-Apr,Electronic City,1 BHK,630,1.0,1.0,40.5,1
6916,Super built-up Area,Ready To Move,Padmanabhanagar,2 BHK,1000,1.0,NaN,90.0,2

In [19]:
df.isnull().sum()

area_type         0
availability      0
location          1
size              0
total_sqft        0
bath              0
balcony         593
price             0
bhk               0
dtype: int64

In [20]:
df['balcony'].value_counts().sort_index()

balcony
0.0    1029
1.0    4897
2.0    5113
3.0    1672
Name: count, dtype: int64

In [21]:
df['balcony'] = df['balcony'].fillna(df['balcony'].median())

In [22]:
df.isnull().sum()

area_type       0
availability    0
location        1
size            0
total_sqft      0
bath            0
balcony         0
price           0
bhk             0
dtype: int64

In [23]:
df = df.dropna()

In [24]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
bhk             0
dtype: int64

In [26]:
df.corr(numeric_only= True)

             bath   balcony     price       bhk
bath     1.000000  0.208333  0.454691  0.895752
balcony  0.208333  1.000000  0.125093  0.194796
price    0.454691  0.125093  1.000000  0.398295
bhk      0.895752  0.194796  0.398295  1.000000

In [27]:
df.cov(numeric_only=True)

              bath    balcony         price        bhk
bath      1.793974   0.224196     90.738744   1.553721
balcony   0.224196   0.645540     14.974877   0.202684
price    90.738744  14.974877  22199.158448  76.851078
bhk       1.553721   0.202684     76.851078   1.677081